
spring.application.name=do_an_ck_J2EE

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false
server.port=8080
server.forward-headers-strategy=framework

# Base URL
app.base-url=http://localhost:8080

# =========================
# MAIL CONFIG
# =========================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tungtan5792@gmail.com
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.mail.from=tungtan5792@gmail.com

# =========================
# GOOGLE LOGIN
# =========================
spring.security.oauth2.client.registration.google.client-id=428753150520-6bp253uso8us5jitjv2gc2ve1lkl5292.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email

# =========================
# FACEBOOK LOGIN
# =========================
spring.security.oauth2.client.registration.facebook.client-id=1438967601058055
spring.security.oauth2.client.registration.facebook.client-secret=${FACEBOOK_SECRET}
spring.security.oauth2.client.registration.facebook.scope=email,public_profile